# Generated by Django 2.0.2 on 2018-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180404_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
